Repository CheerUpTwogether/Piggy, pull requests merged in 2024-10, with the labels that each got.

#283 281 fix alarm all confirm
  src/pages/alarm/Alarm.tsx
Labels: bug

#286 284 약속 생성 실패시 롤백 기능 추가
  src/hooks/useAppointmentFormHooks.tsx
  src/supabase/appointmentSpb.tsx
Labels: bug

#288 279 skeleton 적용
  android/app/src/main/AndroidManifest.xml
  src/components/home/AppointmentItem.tsx
  src/components/home/Profile.tsx
  src/components/skeleton/SkeletonAppointmentItem.tsx
  src/components/skeleton/SkeletonBasicProfile.tsx
  src/components/skeleton/SkeletonFriendItem.tsx
  src/components/skeleton/SkeletonGoodsItem.tsx
  src/components/skeleton/SkeletonHomeProfile.tsx
  src/hooks/useHomeAppointments.tsx
  src/pages/friends/Friends.tsx
  src/pages/goods/Goods.tsx
  src/pages/home/Home.tsx
Labels: enhancement, Publlish

#289 TabBar 컴포넌트 카테고리 별 읽음 상태 추가 구현
  src/components/common/TabBar.tsx
  src/components/frame/TopTab.tsx
  src/pages/alarm/Alarm.tsx
  src/supabase/alarm.ts
  src/types/common.ts
Labels: enhancement

#287 [feat] 약속 거절 시 대기 리스트에서 삭제 기능 구현
  src/components/home/AppointmentItem.tsx
  src/hooks/useHomeAppointments.tsx
  src/pages/home/AppointmentDetail.tsx
  src/pages/home/Home.tsx
  src/store/store.ts
  src/supabase/appointmentSpb.tsx
  src/types/common.ts
Labels: bug

#291 [refactor] #290 약속 시간 누락 -> 추가
  src/components/home/AppointmentItem.tsx
Labels: enhancement

#293 전체 읽음 이펙트 의존성 배열 값 추가
  src/pages/alarm/Alarm.tsx
Labels: bug

#298 codepush 환경 구성
  App.tsx
  android/app/build.gradle
  android/app/src/main/java/com/cheeruptwogether/MainApplication.kt
  android/settings.gradle
  package.json
Labels: enhancement

#301 300 문의하기 사진 잘림 개선
  android/app/src/main/AndroidManifest.xml
  src/components/NoticeBoard/NoticeBoard.tsx
  src/components/common/ToggleButton.tsx
  src/components/setting/HelpDesk.tsx
  src/components/setting/HelpDetail.tsx
  src/pages/settings/Settings.tsx
  src/types/common.ts
Labels: enhancement
