Repository CheerUpTwogether/Piggy, pull requests merged in 2024-08, with the labels that each got.

#5 1 프로젝트 구축
  App.tsx
  babel.config.js
  declarations.d.ts
  metro.config.js
  package.json
  src/pages/Splash.tsx
  src/pages/auth/Login.tsx
  src/pages/friends/Friends.tsx
  src/pages/goods/Goods.tsx
  src/pages/home/Home.tsx
  src/pages/settings/Settings.tsx
  src/router/CustomBottomTab.tsx
  src/router/index.tsx
  src/types/Router.ts
  tsconfig.json
Labels: enhancement

#12 토글버튼 공통 컴포넌트 생성
  src/components/common/ToggleButton.tsx
  src/pages/auth/Login.tsx
  src/types/Common.ts
Labels: enhancement

#43 [feat] #42 supabase 및 env 환경 초기세팅 with(Kakao Login 테스트)
  .env
  App.tsx
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  babel.config.js
  package.json
  src/api/auth.ts
  src/supabase/supabase.ts
Labels: enhancement

#44 [feat] #40 로그인 페이지 화면 구현
  src/assets/icons/kakao.svg
  src/pages/auth/Login.tsx
Labels: enhancement

#47 [styles]#41 공통 스타일 폰트 확립
  android/app/src/main/assets/custom/Pretendard-Bold.woff2
  android/app/src/main/assets/custom/Pretendard-Medium.woff2
  android/app/src/main/assets/custom/Pretendard-Regular.woff2
  android/app/src/main/assets/custom/Pretendard-SemiBold.woff2
  android/app/src/main/assets/custom/PretendardVariable.woff2
  android/link-assets-manifest.json
  ios/link-assets-manifest.json
  src/assets/fonts/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard-Medium.woff2
  src/assets/fonts/Pretendard-Regular.woff2
  src/assets/fonts/Pretendard-SemiBold.woff2
  src/assets/fonts/PretendardVariable.woff2
  src/styles/common.ts
  src/styles/font.ts
Labels: enhancement

#53 49 friends 퍼블리싱
  src/assets/icons/empty.svg
  src/components/common/EmptyResult.tsx
  src/components/frame/TopTab.tsx
  src/mock/Friends/Friends.ts
  src/mock/Friends/type.ts
  src/pages/friends/Friends.tsx
Labels: documentation

#54 51 홈 페이지 퍼블리싱
  src/assets/icons/more.svg
  src/assets/icons/pin.svg
  src/components/common/Button.tsx
  src/components/common/FlatItemsFriends.tsx
  src/components/home/AppointmentItem.tsx
  src/pages/home/Home.tsx
  src/styles/common.ts
  src/styles/font.ts
Labels: Publlish

#55 45 상점 페이지 퍼블리싱
  src/components/frame/TopTab.tsx
  src/components/goods/GoodsDetail.tsx
  src/mook/goods/goods.ts
  src/mook/goods/types.ts
  src/pages/goods/Goods.tsx
  src/router/index.tsx
Labels: enhancement

#61 [styles]#58 스플래시 로고 적용
  src/assets/icons/logo.png
  src/assets/icons/logo.svg
  src/pages/Splash.tsx
  src/pages/auth/Login.tsx
  src/router/index.tsx
Labels: style

#62 57 홈화면 누락된 UI 추가
  src/assets/icons/plus.svg
  src/components/home/AppointmentItem.tsx
  src/components/home/Profile.tsx
  src/mock/Friends/Friends.ts
  src/mock/Friends/type.ts
  src/mock/Home/Home.ts
  src/mock/Home/type.ts
  src/pages/home/Home.tsx
  src/styles/common.ts
Labels: Publlish

#63 52 친구검색 페이지 퍼블리싱
  src/assets/icons/searchFriend.svg
  src/components/common/InputBox.tsx
  src/components/frame/TopTab.tsx
  src/hooks/useDebounce.tsx
  src/mock/Friends/Friends.ts
  src/mock/Friends/type.ts
  src/pages/friends/FriendSearch.tsx
  src/pages/friends/Friends.tsx
  src/router/index.tsx
  src/types/Common.ts
  src/types/Router.ts
Labels: enhancement

#80 64 약속 상세 페이지 퍼블리싱
  src/assets/icons/location.svg
  src/components/home/AppointmentItem.tsx
  src/pages/home/AppointmentDetail.tsx
  src/router/index.tsx
  src/types/Router.ts
Labels: Publlish

#86 77 피기 선물하기 페이지 퍼블리싱
  src/assets/icons/leftArrow.svg
  src/assets/icons/searchFriend.svg
  src/components/frame/TopTab.tsx
  src/pages/friends/FriendSearch.tsx
  src/pages/friends/Friends.tsx
  src/pages/friends/ProfileDetail.tsx
  src/pages/friends/type.ts
  src/pages/gift/ GiftAmount.tsx
  src/pages/gift/GiftFriend.tsx
  src/pages/gift/type.ts
  src/router/index.tsx
  src/types/Router.ts
  src/utils/grade.ts
Labels: Publlish

#83 82 약속 상세 고도화친구 확인 disable처리
  src/components/common/SideSlideModal.tsx
  src/components/home/FriendItem.tsx
  src/mock/Home/Home.ts
  src/mock/Home/type.ts
  src/pages/home/AppointmentDetail.tsx
  src/pages/home/Home.tsx
  src/types/Common.ts
Labels: enhancement

#87 69 피기 사용내역 페이지
  package.json
  src/components/home/Profile.tsx
  src/components/piggy/PiggyUsageItem.tsx
  src/mock/Piggy/Piggy.ts
  src/mock/Piggy/type.ts
  src/pages/auth/Login.tsx
  src/pages/home/Home.tsx
  src/pages/piggy/PiggyUsage.tsx
  src/router/index.tsx
  src/styles/common.ts
  src/types/Router.ts
  yarn.lock
Labels: enhancement

#99 [feat] 공통 컴포넌트 ProgressBar 생성
  src/components/common/ProgressBar.tsx
  src/pages/gift/GiftAmount.tsx
  src/router/index.tsx
  src/types/Common.ts
Labels: enhancement

#92 85 keypad 컴포넌트 예외처리 및 스타일 수정
  src/assets/icons/delete.svg
  src/components/common/Keypad.tsx
  src/components/common/Toast.tsx
  src/types/Common.ts
Labels: enhancement

#102 [fix] #101 Merge 후 TobTab 누락 및 중복 수정
  src/components/frame/TopTab.tsx
Labels: bug

#105 84 알림 페이지 퍼블리싱
  src/assets/icons/appointment.svg
  src/assets/icons/appointmentDelete.svg
  src/assets/icons/appointmentInvite.svg
  src/assets/icons/barcode.svg
  src/assets/icons/clock.svg
  src/assets/icons/coin.svg
  src/components/common/TabBar.tsx
  src/components/frame/TopTab.tsx
  src/components/piggy/PiggyUsageItem.tsx
  src/mock/Alarm/Alarm.ts
  src/mock/Alarm/type.ts
  src/pages/alarm/Alarm.tsx
  src/pages/friends/Friends.tsx
  src/pages/goods/Goods.tsx
  src/pages/home/Home.tsx
  src/router/index.tsx
  src/types/Common.ts
  src/types/Router.ts
  src/utils/date.ts
Labels: enhancement

#103 100 feat appointment
  .gitignore
  android/app/src/main/AndroidManifest.xml
  declarations.d.ts
  ios/piggy.xcodeproj/project.pbxproj
  package.json
  src/api/kakao/map.ts
  src/assets/icons/calendar.svg
  src/assets/icons/locationCircle.svg
  src/assets/icons/locationFlag.svg
  src/assets/icons/locationRoad.svg
  src/assets/icons/people.svg
  src/assets/icons/roundHandshake.svg
  src/components/appointment/AppointmentCalendar.tsx
  src/components/appointment/AppointmentCheck.tsx
  src/components/appointment/AppointmentFriend.tsx
  src/components/appointment/AppointmentPenalty.tsx
  src/components/appointment/AppointmentPlace.tsx
  src/components/appointment/TimePicker.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/FlatItemsFriends.tsx
  src/components/common/InputBox.tsx
  src/components/common/Keypad.tsx
  src/components/common/Toast.tsx
  src/components/frame/TopTab.tsx
  src/hooks/useLocation.ts
  src/mock/Friends/Friends.ts
  src/mock/Friends/type.ts
  src/mock/Home/Home.ts
  src/mock/Place/Place.ts
  src/mock/Place/type.ts
  src/pages/friends/FriendSearch.tsx
  src/pages/friends/Friends.tsx
  src/pages/friends/ProfileDetail.tsx
  src/pages/gift/GiftAmount.tsx
  src/pages/home/AppointmentForm.tsx
  src/pages/home/Home.tsx
  src/pages/home/type.ts
  src/router/index.tsx
  src/styles/common.ts
  src/types/Common.ts
  src/types/Router.ts
  src/utils/distance.ts
  src/utils/permission.ts
  src/utils/timePicker.ts
Labels: enhancement

#112 109 button modal common component
  src/components/common/ButtonBottomSheet.tsx
  src/components/frame/BottomTab.tsx
  src/pages/friends/Friends.tsx
  src/types/Common.ts
Labels: enhancement

#111 110 input 컴포넌트 props 추가
  src/assets/icons/check.svg
  src/assets/icons/phone.svg
  src/components/common/CheckBox.tsx
  src/components/common/InputBox.tsx
  src/pages/auth/LoginDetail.tsx
  src/pages/auth/LoginDetailForm.tsx
  src/types/Common.ts
Labels: enhancement

#117 113 홈화면 바뀐 디자인 적용
  src/assets/icons/cancelCalendar.svg
  src/assets/icons/empty.svg
  src/assets/icons/pending.svg
  src/components/appointment/AppointmentFriend.tsx
  src/components/home/AppointmentItem.tsx
  src/mock/Alarm/Alarm.ts
  src/mock/Home/Home.ts
  src/mock/Home/type.ts
  src/pages/alarm/Alarm.tsx
  src/pages/auth/LoginDetailForm.tsx
  src/pages/home/AppointmentDetail.tsx
  src/pages/home/Home.tsx
Labels: enhancement

#126 125 상점 페이지 디자인 변경
  src/components/goods/GoodsDetail.tsx
  src/mock/Goods/Goods.ts
  src/mock/Goods/types.ts
  src/pages/goods/Goods.tsx
  src/pages/goods/type.ts
Labels: enhancement

#128 127 사전 출시 보고서 접근성 개선
  src/assets/icons/google.svg
  src/components/NoticeBoard/NoticeBoardDetail.tsx
  src/components/appointment/AppointmentCheck.tsx
  src/components/appointment/AppointmentFriend.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/Button.tsx
  src/components/common/ButtonBottomSheet.tsx
  src/components/common/CheckBox.tsx
  src/components/common/FlatItemsFriends.tsx
  src/components/common/InputBox.tsx
  src/components/common/TabBar.tsx
  src/components/frame/BottomTab.tsx
  src/components/frame/TopTab.tsx
  src/components/goods/GoodsDetail.tsx
  src/components/goodsStorage/GoodsStorage.tsx
  src/components/goodsStorage/GoodsStorageDetail.tsx
  src/components/home/FriendItem.tsx
  src/components/home/Profile.tsx
  src/components/piggy/PiggyUsageItem.tsx
  src/components/setting/EditProfile.tsx
  src/components/setting/HelpDesk.tsx
  src/components/setting/HelpDetail.tsx
  src/components/userAgreement/PaymentAgreement.tsx
  src/components/userAgreement/ServiceAgreement.tsx
  src/pages/Splash.tsx
  src/pages/auth/Login.tsx
  src/pages/auth/LoginDetail.tsx
  src/pages/friends/FriendSearch.tsx
  src/pages/friends/Friends.tsx
  src/pages/friends/ProfileDetail.tsx
  src/pages/gift/GiftAmount.tsx
  src/pages/goods/Goods.tsx
  src/pages/home/AppointmentDetail.tsx
  src/pages/piggy/PiggyUsage.tsx
  src/pages/settings/Settings.tsx
  src/types/Common.ts
Labels: enhancement
